"""
This type stub file was generated by pyright.
"""

import re
import yaml
import toml
from types import ModuleType
from typing import Any, TYPE_CHECKING, Type
from yaml import CSafeDumper as SafeDumper, CSafeLoader as SafeLoader
from frontmatter import Post

"""
This type stub file was generated by pyright.
"""
SafeDumper: Type[yaml.CDumper] | Type[yaml.SafeDumper]
SafeLoader: Type[yaml.CSafeLoader] | Type[yaml.SafeLoader]
toml: ModuleType | None
if TYPE_CHECKING:
    ...
__all__ = ["BaseHandler", "YAMLHandler", "JSONHandler"]
if toml:
    ...
DEFAULT_POST_TEMPLATE = ...
class BaseHandler:
    """
    BaseHandler lays out all the steps to detecting, splitting, parsing and
    exporting front matter metadata.

    All default handlers are subclassed from BaseHandler.
    """
    FM_BOUNDARY: re.Pattern[str] | None = ...
    START_DELIMITER: str | None = ...
    END_DELIMITER: str | None = ...
    def __init__(self, fm_boundary: re.Pattern[str] | None = ..., start_delimiter: str | None = ..., end_delimiter: str | None = ...) -> None:
        ...
    
    def detect(self, text: str) -> bool:
        """
        Decide whether this handler can parse the given ``text``,
        and return True or False.

        Note that this is *not* called when passing a handler instance to
        :py:func:`frontmatter.load <frontmatter.load>` or :py:func:`loads <frontmatter.loads>`.
        """
        ...
    
    def split(self, text: str) -> tuple[str, str]:
        """
        Split text into frontmatter and content
        """
        ...
    
    def load(self, fm: str) -> dict[str, Any]:
        """
        Parse frontmatter and return a dict
        """
        ...
    
    def export(self, metadata: dict[str, object], **kwargs: object) -> str:
        """
        Turn metadata back into text
        """
        ...
    
    def format(self, post: Post, **kwargs: object) -> str:
        """
        Turn a post into a string, used in ``frontmatter.dumps``
        """
        ...
    


class YAMLHandler(BaseHandler):
    """
    Load and export YAML metadata. By default, this handler uses YAML's
    "safe" mode, though it's possible to override that.
    """
    FM_BOUNDARY = ...
    END_DELIMITER = ...
    def load(self, fm: str, **kwargs: object) -> Any:
        """
        Parse YAML front matter. This uses yaml.SafeLoader by default.
        """
        ...
    
    def export(self, metadata: dict[str, object], **kwargs: object) -> str:
        """
        Export metadata as YAML. This uses yaml.SafeDumper by default.
        """
        ...
    


class JSONHandler(BaseHandler):
    """
    Load and export JSON metadata.

    Note that changing ``START_DELIMITER`` or ``END_DELIMITER`` may break JSON parsing.
    """
    FM_BOUNDARY = ...
    START_DELIMITER = ...
    END_DELIMITER = ...
    def split(self, text: str) -> tuple[str, str]:
        ...
    
    def load(self, fm: str, **kwargs: object) -> Any:
        ...
    
    def export(self, metadata: dict[str, object], **kwargs: object) -> str:
        "Turn metadata into JSON"
        ...
    


if toml:
    class TOMLHandler(BaseHandler):
        """
        Load and export TOML metadata.

        By default, split based on ``+++``.
        """
        FM_BOUNDARY = ...
        END_DELIMITER = ...
        def load(self, fm: str, **kwargs: object) -> Any:
            ...
        
        def export(self, metadata: dict[str, object], **kwargs: object) -> str:
            "Turn metadata into TOML"
            ...
        
    
    
else:
    TOMLHandler: Type[TOMLHandler] | None = ...
