"""
This type stub file was generated by pyright.
"""

from typing import AnyStr

"""
This type stub file was generated by pyright.
"""
def u(text: AnyStr, encoding: str = ...) -> str:
    "Return unicode text, no matter what"
    ...

